# Generated by Django 5.0.7 on 2025-02-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_customercomplaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='resolvedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
